// 开源模板库数据
// 来源：本地 Front-End 归档中识别出的「纯上游开源模板」（此前判为 D 类，未移植）。
// 全部为公开上游开源项目，仅收录名称 / 技术栈 / 能力点等元信息，不含任何内部代码或敏感数据。
// upstream 为各项目公开仓库地址（可点击溯源）；无独立公开仓库的标记为 null。

export const TEMPLATES = [
  /* ============ React 中后台 / 脚手架 ============ */
  {
    id: 'ant-design-pro',
    name: 'Ant Design Pro',
    framework: 'React',
    group: 'React',
    category: '企业级中后台脚手架',
    upstream: 'https://github.com/ant-design/ant-design-pro',
    desc: '蚂蚁官方出品的成熟中后台解决方案，约定优于配置，覆盖绝大多数后台场景。',
    features: [
      '开箱即用的中后台布局与登录鉴权',
      'ProLayout / ProTable / ProForm 等 Pro 组件',
      '权限路由 + 国际化 + 多主题',
      '图表、列表、结果页等页面模板',
    ],
    tags: ['中后台', 'antd', 'umi'],
  },
  {
    id: 'antd-admin',
    name: 'antd-admin',
    framework: 'React',
    group: 'React',
    category: '轻量中后台模板',
    upstream: 'https://github.com/zuiidea/antd-admin',
    desc: '基于 antd 的轻量后台模板，比 Pro 更简洁，适合快速起步。',
    features: ['菜单/路由自动生成', '权限与角色控制', '国际化与暗黑主题', '常用业务页面示例'],
    tags: ['中后台', 'antd'],
  },
  {
    id: 'react-admin-duxianwei',
    name: 'react (duxianwei520)',
    framework: 'React',
    group: 'React',
    category: '经典后台管理模板',
    upstream: 'https://github.com/duxianwei520/react',
    desc: 'React16 + redux + react-router + webpack + antd3 的完整后台模板，社区经典。',
    features: ['redux 状态管理 + axios 封装', '动态路由与权限', '表格/表单/图表示例', '登录与布局骨架'],
    tags: ['中后台', 'redux'],
  },
  {
    id: 'react-admin-yezihaohao',
    name: 'react-admin (yezihaohao)',
    framework: 'React',
    group: 'React',
    category: '权限后台解决方案',
    upstream: 'https://github.com/yezihaohao/react-admin',
    desc: 'React + antd 的后台解决方案，附在线可编辑 demo，权限与动态路由实现清晰。',
    features: ['权限菜单与动态路由', '角色级访问控制', '表格/表单模板', '在线编辑示例'],
    tags: ['中后台', '权限'],
  },
  {
    id: 'react-admin-z9527',
    name: 'react-admin-master (z-9527)',
    framework: 'React',
    group: 'React',
    category: '入门练习模板',
    upstream: 'https://github.com/z-9527/react-admin-master',
    desc: '业余时间基于 React + antd 写的管理模板，以展示型页面为主，适合入门学习。',
    features: ['React + antd 基础用法', '展示型页面为主', '轻量无后台依赖', '适合熟悉 antd 组件'],
    tags: ['中后台', '入门'],
  },
  {
    id: 'react-xs-admin',
    name: 'react-xs-admin',
    framework: 'React',
    group: 'React',
    category: 'Vite + TS 现代后台',
    upstream: 'https://github.com/jsxiaosi/react-xs-admin',
    desc: 'React18 + antd5 + Vite + TS 的现代后台模板，构建快、类型安全。',
    features: ['Vite 极速构建', 'TypeScript 类型安全', '权限与多主题', '组件/接口分层示例'],
    tags: ['中后台', 'vite', 'TS'],
  },
  {
    id: 'react-boilerplate',
    name: 'react-boilerplate',
    framework: 'React',
    group: 'React',
    category: '工程化脚手架',
    upstream: 'https://github.com/react-boilerplate/react-boilerplate',
    desc: '老牌 React 项目脚手架，强调工程化最佳实践（redux-saga / 代码分割 / i18n）。',
    features: ['redux-saga 异步流', '代码分割与懒加载', '国际化骨架', '可复用的工程化约定'],
    tags: ['脚手架', 'boilerplate'],
  },

  /* ============ Vue 中后台 / 脚手架 ============ */
  {
    id: 'vue-element-admin',
    name: 'vue-element-admin',
    framework: 'Vue',
    group: 'Vue',
    category: '最知名中后台模板',
    upstream: 'https://github.com/PanJiaChen/vue-element-admin',
    desc: 'Vue2 + element-ui 的中后台标杆模板，生态成熟、示例最丰富。',
    features: ['动态路由与权限', 'Mock 数据与国际化', '丰富组件示例', '登录/布局/错误页模板'],
    tags: ['中后台', 'element-ui'],
  },
  {
    id: 'vue-ts-admin',
    name: 'vue-typescript-admin-template',
    framework: 'Vue',
    group: 'Vue',
    category: 'TS 中后台模板',
    upstream: 'https://github.com/armour/vue-typescript-admin-template',
    desc: 'Vue + TypeScript + element-ui 的中后台模板，强调类型安全。',
    features: ['TypeScript 类型安全', '权限与多标签页', 'axios 封装', '常用业务页面'],
    tags: ['中后台', 'TS'],
  },
  {
    id: 'vue-cli-pc',
    name: 'vue-cli-pc',
    framework: 'Vue',
    group: 'Vue',
    category: 'PC 后台基础模板（基座）',
    upstream: null,
    desc: '基于 vue-cli + element-ui 的 PC 端后台基础模板，是多个衍生项目的共同基座。',
    features: ['登录/布局/菜单骨架', '表格与表单示例', 'element-ui 组件集成', '可作为二次开发基座'],
    tags: ['中后台', 'element-ui', '基座'],
  },
  {
    id: 'cemao-pc',
    name: 'cemao-pc',
    framework: 'Vue',
    group: 'Vue',
    category: 'vue-cli-pc 衍生项目',
    upstream: null,
    desc: '在 vue-cli-pc 基座上做业务定制的衍生项目，共享同一套后台骨架。',
    features: ['复用 vue-cli-pc 基座', '业务页定制', 'element-ui 组件', '本地派生（无公开仓库）'],
    tags: ['中后台', '衍生'],
    derived: true,
  },
  {
    id: 'erp-cm-admin',
    name: 'erp-cm-admin',
    framework: 'Vue',
    group: 'Vue',
    category: 'vue-cli-pc 衍生项目',
    upstream: null,
    desc: '基于 vue-cli-pc 基座的中后台衍生项目，结构与 cemao-pc 同源。',
    features: ['复用 vue-cli-pc 基座', '业务页定制', 'element-ui 组件', '本地派生（无公开仓库）'],
    tags: ['中后台', '衍生'],
    derived: true,
  },
  {
    id: 'erp-supervise',
    name: 'erp-supervise',
    framework: 'Vue',
    group: 'Vue',
    category: 'cemao-pc 衍生项目',
    upstream: null,
    desc: '在 cemao-pc 派生链上的二次项目，同基座衍生。',
    features: ['复用 cemao-pc 基座', '业务页定制', 'element-ui 组件', '本地派生（无公开仓库）'],
    tags: ['中后台', '衍生'],
    derived: true,
  },
  {
    id: 'web-carpool',
    name: 'web-carpool',
    framework: 'Vue',
    group: 'Vue',
    category: 'cemao-pc 衍生项目',
    upstream: null,
    desc: '在 cemao-pc 派生链上的二次项目，同基座衍生。',
    features: ['复用 cemao-pc 基座', '业务页定制', 'element-ui 组件', '本地派生（无公开仓库）'],
    tags: ['中后台', '衍生'],
    derived: true,
  },
  {
    id: 'webpool',
    name: 'webpool',
    framework: 'Vue',
    group: 'Vue',
    category: 'cemao-pc 衍生项目',
    upstream: null,
    desc: '在 cemao-pc 派生链上的二次项目，同基座衍生。',
    features: ['复用 cemao-pc 基座', '业务页定制', 'element-ui 组件', '本地派生（无公开仓库）'],
    tags: ['中后台', '衍生'],
    derived: true,
  },
  {
    id: 'asunrabbit',
    name: 'asunrabbit (Vite Vue-TS)',
    framework: 'Vue',
    group: 'Vue',
    category: 'Vite + TS 起步脚手架',
    upstream: null,
    desc: '基于官方 Vite Vue3 + TypeScript 脚手架的起步项目，含 <script setup> 写法。',
    features: ['Vue3 + Vite 极速启动', 'TypeScript + <script setup>', '推荐 IDE 配置', '最小可运行骨架'],
    tags: ['脚手架', 'vite', 'TS'],
  },

  /* ============ 移动端 ============ */
  {
    id: 'mobvue',
    name: 'MobVue',
    framework: 'Mobile',
    group: '移动端',
    category: '移动端 Vue 模板',
    upstream: 'https://github.com/un-pany/mobvue',
    desc: 'Mobile + Vue 的移动端开发模板，封装常见移动端布局与组件。',
    features: ['移动端路由与布局', '状态管理示例', '常用移动组件', '适配与交互封装'],
    tags: ['移动端', 'Vue'],
  },

  /* ============ 组件库 / 工具 ============ */
  {
    id: 'element-plus',
    name: 'Element Plus',
    framework: 'Lib',
    group: '组件库·工具',
    category: 'Vue3 组件库',
    upstream: 'https://github.com/element-plus/element-plus',
    desc: 'Vue3 的成熟组件库本体，提供 80+ 组件，是众多 Vue 后台的底座。',
    features: ['80+ 高质量组件', '暗黑模式与主题定制', '国际化', '表单/表格/弹窗等完整体系'],
    tags: ['组件库', 'Vue3'],
  },
  {
    id: 'pdf-js',
    name: 'PDF.js',
    framework: 'Lib',
    group: '组件库·工具',
    category: 'PDF 渲染库',
    upstream: 'https://github.com/mozilla/pdf.js',
    desc: 'Mozilla 出品的 HTML5 PDF 渲染库，纯前端解析与展示 PDF。',
    features: ['纯前端 PDF 渲染', '文本层与注解支持', 'Web Worker 解析', '可嵌入任意页面'],
    tags: ['PDF', '工具库'],
  },
]

/* 过滤分组（用于顶部 Segmented 切换） */
export const GROUPS = [
  { key: 'all', label: '全部' },
  { key: 'React', label: 'React' },
  { key: 'Vue', label: 'Vue' },
  { key: '移动端', label: '移动端' },
  { key: '组件库·工具', label: '组件库·工具' },
]

/* 框架 → 主题色（与 --c-* 设计系统对齐） */
export const FRAMEWORK_COLOR = {
  React: '#1677ff',
  Vue: '#13c2c2',
  Mobile: '#722ed1',
  Lib: '#fa8c16',
}
